/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    screens: {
      xs: '320px',
      sm: '375px',
      md: '640px',
      lg: '768px',
      xl: '1024px',
      '2xl': '1280px',
      '3xl': '1536px',
      '4xl': '1680px',
      '5xl': '1920px',
      ultra: '1680px',
      cinema: '2048px',
      wall: '2560px',
      tablet: '768px',
      desktop: '1024px',
      wide: '1280px',
    },
    extend: {
      colors: {
        primary: 'rgb(var(--primary) / <alpha-value>)',
        'primary-hover': 'rgb(var(--primary-hover) / <alpha-value>)',
        'primary-active': 'rgb(var(--primary-active) / <alpha-value>)',
        'primary-dark': 'rgb(var(--primary-dark) / <alpha-value>)',
        navy: 'rgb(var(--navy) / <alpha-value>)',
        'surface-dark': 'rgb(var(--surface-dark) / <alpha-value>)',
        'surface-blue': 'rgb(var(--surface-blue) / <alpha-value>)',
        'border-blue': 'rgb(var(--border-blue) / <alpha-value>)',
        highlight: 'rgb(var(--highlight) / <alpha-value>)',
        'text-on-dark': 'rgb(var(--text-on-dark) / <alpha-value>)',
        'text-primary': 'rgb(var(--text-primary) / <alpha-value>)',
        'text-muted': 'rgb(var(--text-muted) / <alpha-value>)',
        'surface-page': 'rgb(var(--surface-page) / <alpha-value>)',
        'surface-card': 'rgb(var(--surface-card) / <alpha-value>)',
        'surface-subtle': 'rgb(var(--surface-subtle) / <alpha-value>)',
        'border-default': 'rgb(var(--border-default) / <alpha-value>)',
        text: 'rgb(var(--text-primary) / <alpha-value>)',
        border: 'rgb(var(--border-default) / <alpha-value>)',
        'brand-navy': 'rgb(var(--navy) / <alpha-value>)',
        'brand-ink': 'rgb(var(--surface-blue) / <alpha-value>)',
        'brand-gold': 'rgb(var(--brand-gold) / <alpha-value>)',
        'brand-gold-soft': 'rgb(var(--brand-gold-soft) / <alpha-value>)',
        'status-available': 'rgb(var(--status-available) / <alpha-value>)',
        'status-available-bg': 'rgb(var(--status-available-bg) / <alpha-value>)',
        'status-incoming': 'rgb(var(--status-incoming) / <alpha-value>)',
        'status-incoming-bg': 'rgb(var(--status-incoming-bg) / <alpha-value>)',
        'status-reserved': 'rgb(var(--status-reserved) / <alpha-value>)',
        'status-reserved-bg': 'rgb(var(--status-reserved-bg) / <alpha-value>)',
        'status-sold': 'rgb(var(--status-sold) / <alpha-value>)',
        'status-sold-bg': 'rgb(var(--status-sold-bg) / <alpha-value>)',
        'status-info': 'rgb(var(--status-info) / <alpha-value>)',
        'status-info-bg': 'rgb(var(--status-info-bg) / <alpha-value>)',
        'status-neutral': 'rgb(var(--status-neutral) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['"IBM Plex Sans"', '"Segoe UI"', 'sans-serif'],
        display: ['"IBM Plex Sans Condensed"', '"IBM Plex Sans"', 'sans-serif'],
      },
      boxShadow: {
        card: '0 1px 2px rgba(3, 16, 65, 0.04)',
        hover: '0 3px 10px rgba(3, 16, 65, 0.07)',
        dropdown: '0 14px 30px rgba(3, 16, 65, 0.12)',
      },
      borderRadius: {
        xl: '2px',
        '2xl': '2px',
        '3xl': '2px',
      },
    },
  },
  plugins: [],
};
